# Generated by Django 4.2.6 on 2024-03-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aereopuerto',
            fields=[
                ('id_aero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'aereopuerto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id_avion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('alcance', models.CharField(blank=True, max_length=255, null=True)),
                ('vel_crucero', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'avion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvionCarga',
            fields=[
                ('id_ac', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_carga', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'avion_carga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvionFabricante',
            fields=[
                ('id_fabricante', models.IntegerField(primary_key=True, serialize=False)),
                ('fabricante', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'avion_fabricante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id_bol', models.IntegerField(primary_key=True, serialize=False)),
                ('num_asociado_reserva', models.IntegerField(blank=True, null=True)),
                ('asiento', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'boleto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('cuarentena', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emp', models.IntegerField(primary_key=True, serialize=False)),
                ('sexo', models.TextField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('turno_trabajo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_contrato', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id_fabricante', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('cuarentena', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fabricante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.IntegerField(primary_key=True, serialize=False)),
                ('horario', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id_pasajero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pasajero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('chequeada', models.BooleanField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentoVuelo',
            fields=[
                ('id_segmento', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('clase', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'segmento_vuelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tramo',
            fields=[
                ('id_tramo', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tramo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ci', models.CharField(db_column='CI', primary_key=True, serialize=False)),
                ('contraseña', models.CharField()),
                ('rol', models.CharField()),
                ('nombreusuario', models.CharField(db_column='nombreUsuario')),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id_vuelo', models.IntegerField(primary_key=True, serialize=False)),
                ('origen', models.CharField(blank=True, max_length=255, null=True)),
                ('destino', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vuelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvionAeropuerto',
            fields=[
                ('id_aero', models.OneToOneField(db_column='id_aero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hilink.aereopuerto')),
            ],
            options={
                'db_table': 'avion_aeropuerto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvionSegmentoVuelo',
            fields=[
                ('id_avion', models.OneToOneField(db_column='id_avion', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hilink.avion')),
            ],
            options={
                'db_table': 'avion_segmento_vuelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservaSegmento',
            fields=[
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('id_reserva', models.OneToOneField(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hilink.reserva')),
            ],
            options={
                'db_table': 'reserva_segmento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VueloHorario',
            fields=[
                ('id_vuelo', models.OneToOneField(db_column='id_vuelo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hilink.vuelo')),
            ],
            options={
                'db_table': 'vuelo_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VueloSegmentoVuelo',
            fields=[
                ('id_vuelo', models.OneToOneField(db_column='id_vuelo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hilink.vuelo')),
            ],
            options={
                'db_table': 'vuelo_segmento_vuelo',
                'managed': False,
            },
        ),
    ]
